### ISSUE TITLE
Issues with the new version

### ISSUE THREAD

**Issue by dop2000** [Armaldio/refined-construct-3#33]
Hey, thanks for this extension! It was working great until recently. 
After the latest update the search box in Debug Mode moved and now it doesn't filter the list of objects:

![image](https://user-images.githubusercontent.com/36763350/129342932-4b208f89-2dc2-4ea1-8812-d9f129bdf5ab.png)

And another problem is that it fills console log with these messages:

![image](https://user-images.githubusercontent.com/36763350/129342809-ce965570-3c76-4745-a64d-6b964326b7fc.png)

**Comment by Armaldio** [comment]
Thanks for the report!

1. I'll remove the logging
2. The filtering works fine for me
Do you have detailed steps to reproduce the issue ?

https://user-images.githubusercontent.com/3089715/129349967-810269a6-7d70-4e74-aed0-57f8c6ab70ad.mp4

**Comment by dop2000** [comment]
2. When you type something in the search box, a few objects disappear from the list, but lots of other objects remain their, even if they don't contain the search phrase.
You can actually see it in your video - you typed "titlesc" and the list shows objects with names like Spritefont or Collectibles for some reason.

**Comment by Armaldio** [comment]
No, you're right!
At first, I tought the search didn't worked at all

The search has changed a bit since last time (strict -> fuzzy) and I didn't realized that some matches were wrong.

I have enforced the fuzziness. Is it better ?
https://user-images.githubusercontent.com/3089715/129351889-0f91587d-0f3f-456a-a79a-c7573ceea3dd.mp4

**Comment by dop2000** [comment]
Yep, perfect, thanks for fixing it! Can't imaging debugging without this extension now! :)

**Comment by Armaldio** [comment]
fixed by 02f6aeca01df0da1ab039059ce6f4d4e4fcb1386, sorry for the trouble

Don't forget to suggest more features!

**Comment by Armaldio** [comment]
Published
